#ifndef _AROSDEFINITIONS_H
#define _AROSDEFINITIONS_H

#define AROS_COMM_WIRE_ADD 8
#define AROS_MASTER_WIRE_ADD 9
#define AROS_AVAILABLE_PACKET "AVAILABL"
#define AROS_BROADCAST_ADDR "255.255.255.255"
#define AROS_DEFAULT_PORT 2000
#define AROS_MAX_REMOTES 2
#define AROS_MAX_VECTORS 4
#define AROS_TOKEN_CMD 1UL
#define AROS_TOKEN_POS 2UL
#define AROS_TOKEN_REL 3UL
#define AROS_TOKEN_FRE 4UL
#define AROS_TOKEN_END 5UL
#define AROS_TRANSPORT_END 6UL

#define MOTOR_COMMAND_LINE_FOLLOW 0x01 << 0
#define MOTOR_COMMAND_TURN_ARROUND 0x01 << 1
#define MOTOR_COMMAND_LINE_FOLLOW_END 0x01 << 2
#define MOTOR_COMMAND_TURN_ARROUND_END 0x01 << 3

#endif
