#ifndef _AROSDEFINITIONS_H
#define _AROSDEFINITIONS_H

#define AROS_COMM_WIRE_ADD 8
#define AROS_MASTER_WIRE_ADD 9
#define AROS_AVAILABLE_PACKET "AVAILABL"
#define AROS_BROADCAST_ADDR "255.255.255.255"
#define AROS_DEFAULT_PORT 2000
#define AROS_MAX_REMOTES 2
#define AROS_MAX_VECTORS 4

#define MOTOR_COMMAND_LINE_FOLLOW 0x01 << 0
#define MOTOR_COMMAND_TURN_ARROUND 0x01 << 1

#endif
