#ifndef _AROSDEFINITIONS_H
#define _AROSDEFINITIONS_H

#define AROS_COMM_WIRE_ADD 8
#define AROS_MASTER_WIRE_ADD 9
#define AROS_AVAILABLE_PACKET "AVAILABL"
#define AROS_BROADCAST_ADDR "255.255.255.255"

#endif
